id: P7A8F0B1E
initial_creation_type: input
source_metadata:
  title: Dying and the Bardos
  language: en
  description: 'Lotsawa House presents the following texts as part of our Dying and
    Bardos Series:'
  volume:
    79f6227ddbcf4637b3a6576180054e91:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Dying
    6797109a42de406184c6c83cfc44c9b8:
      title: The Noble Sūtra Teaching the Eleven Perceptions
      parent: Dying
    77dee195f9244fedb381d8a0ba4989e3:
      title: Advice for Hor Özer
      parent: Dying
    d7b56b88eddd473a815068be1690c6bf:
      title: Advice for a Dying Practitioner
      parent: Dying
    6083ae562a85478c9784c457afe4dfe6:
      title: Aspiration at the Moment of Death
      parent: Dying
    b437072fc96648538451999b83093733:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Dying
    a57a24365f7c49e6a2a66c13fd8db5a8:
      title: A Wondrous Instruction for the Moment of Death
      parent: Dying
    0dcdf611bd934d669e4b3d4b02216878:
      title: Meditation on Amitābha
      parent: Dying
    81397ebb994841db9a75c1db4c25d088:
      title: The Root Verses on the Six Bardos
      parent: Bardos
    8cfb8ccdf5fe484ba0bb177661292cbb:
      title: 'Crucial Advice: A Complete Set of Instructions for the Bardos'
      parent: Bardos
    fd3390f3236a4f9abb12a51a988d89b7:
      title: 'Liberation Upon Hearing: An Explanation of the Phenomena of the Intermediate
        State'
      parent: Bardos
    45420126115d4ed99b25c2b04cae053e:
      title: A Brief Introduction to the Bardos
      parent: Bardos
    57abcdd23647494d9fda879a18af9466:
      title: 'Fostering Recollection to Dispel the Torment of Deluded Perception:
        An Aspiration for the Bardos'
      parent: Prayers
    04185cf998b14fa697a9b4c817af4a7b:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Prayers
    60e7927d2ecb4406b8d0ed97a5613398:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Prayers
    8e736f2c96464c80bf159f5d732f7034:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
created_at: '2022-03-01T03:30:40.701777'
last_modified_at: '2022-03-01T03:30:40.701784'
